# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReviewTag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReviewTag.proto',
  package='ReviewTagGeneration',
  serialized_pb=_b('\n\x0fReviewTag.proto\x12\x13ReviewTagGeneration\"\x93\x01\n\x03Tag\x12\x0f\n\x07\x63ontent\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12,\n\x07jj_list\x18\x05 \x03(\x0b\x32\x1b.ReviewTagGeneration.Tag.JJ\x1a!\n\x02JJ\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\"4\n\x06\x41llTag\x12*\n\x08\x61ll_tags\x18\x01 \x03(\x0b\x32\x18.ReviewTagGeneration.Tag')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TAG_JJ = _descriptor.Descriptor(
  name='JJ',
  full_name='ReviewTagGeneration.Tag.JJ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ReviewTagGeneration.Tag.JJ.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='ReviewTagGeneration.Tag.JJ.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=188,
)

_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='ReviewTagGeneration.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='ReviewTagGeneration.Tag.content', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='ReviewTagGeneration.Tag.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ReviewTagGeneration.Tag.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='ReviewTagGeneration.Tag.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jj_list', full_name='ReviewTagGeneration.Tag.jj_list', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TAG_JJ, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=188,
)


_ALLTAG = _descriptor.Descriptor(
  name='AllTag',
  full_name='ReviewTagGeneration.AllTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='all_tags', full_name='ReviewTagGeneration.AllTag.all_tags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=242,
)

_TAG_JJ.containing_type = _TAG
_TAG.fields_by_name['jj_list'].message_type = _TAG_JJ
_ALLTAG.fields_by_name['all_tags'].message_type = _TAG
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['AllTag'] = _ALLTAG

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(

  JJ = _reflection.GeneratedProtocolMessageType('JJ', (_message.Message,), dict(
    DESCRIPTOR = _TAG_JJ,
    __module__ = 'ReviewTag_pb2'
    # @@protoc_insertion_point(class_scope:ReviewTagGeneration.Tag.JJ)
    ))
  ,
  DESCRIPTOR = _TAG,
  __module__ = 'ReviewTag_pb2'
  # @@protoc_insertion_point(class_scope:ReviewTagGeneration.Tag)
  ))
_sym_db.RegisterMessage(Tag)
_sym_db.RegisterMessage(Tag.JJ)

AllTag = _reflection.GeneratedProtocolMessageType('AllTag', (_message.Message,), dict(
  DESCRIPTOR = _ALLTAG,
  __module__ = 'ReviewTag_pb2'
  # @@protoc_insertion_point(class_scope:ReviewTagGeneration.AllTag)
  ))
_sym_db.RegisterMessage(AllTag)


# @@protoc_insertion_point(module_scope)
