# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeneralUsage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GeneralUsage.proto',
  package='com.fuhu.hadoop',
  serialized_pb=_b('\n\x12GeneralUsage.proto\x12\x0f\x63om.fuhu.hadoop\"\xc6\x02\n\x0fGeneralUsagePro\x12\x13\n\x0b\x63\x61pturetime\x18\x01 \x01(\x03\x12\x12\n\nuploadTime\x18\x02 \x01(\x03\x12\x11\n\tdeviceKey\x18\x03 \x01(\t\x12\x12\n\ndeviceType\x18\x04 \x01(\t\x12\x16\n\x0e\x61ndroidVersion\x18\x05 \x01(\t\x12\x15\n\rdeviceEdition\x18\x06 \x01(\t\x12\x1b\n\x13nabiFirmwareVersion\x18\x07 \x01(\t\x12\x1a\n\x12\x63lientAgentVersion\x18\x08 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\t \x01(\t\x12\x0c\n\x04lang\x18\n \x01(\t\x12\x11\n\tipAddress\x18\x0b \x01(\t\x12\x12\n\nmacAddress\x18\x0c \x01(\t\x12\x10\n\x08timeZone\x18\r \x01(\t\x12\r\n\x05\x65xtra\x18\x0e \x01(\t\x12\x10\n\x08\x62odydata\x18\x0f \x01(\tB.\n\x1a\x63om.fuhu.usagetracking.dtoB\x10GeneralUsageData')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENERALUSAGEPRO = _descriptor.Descriptor(
  name='GeneralUsagePro',
  full_name='com.fuhu.hadoop.GeneralUsagePro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capturetime', full_name='com.fuhu.hadoop.GeneralUsagePro.capturetime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uploadTime', full_name='com.fuhu.hadoop.GeneralUsagePro.uploadTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceKey', full_name='com.fuhu.hadoop.GeneralUsagePro.deviceKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceType', full_name='com.fuhu.hadoop.GeneralUsagePro.deviceType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='androidVersion', full_name='com.fuhu.hadoop.GeneralUsagePro.androidVersion', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceEdition', full_name='com.fuhu.hadoop.GeneralUsagePro.deviceEdition', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nabiFirmwareVersion', full_name='com.fuhu.hadoop.GeneralUsagePro.nabiFirmwareVersion', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientAgentVersion', full_name='com.fuhu.hadoop.GeneralUsagePro.clientAgentVersion', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='countryCode', full_name='com.fuhu.hadoop.GeneralUsagePro.countryCode', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lang', full_name='com.fuhu.hadoop.GeneralUsagePro.lang', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipAddress', full_name='com.fuhu.hadoop.GeneralUsagePro.ipAddress', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='macAddress', full_name='com.fuhu.hadoop.GeneralUsagePro.macAddress', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeZone', full_name='com.fuhu.hadoop.GeneralUsagePro.timeZone', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra', full_name='com.fuhu.hadoop.GeneralUsagePro.extra', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bodydata', full_name='com.fuhu.hadoop.GeneralUsagePro.bodydata', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=366,
)

DESCRIPTOR.message_types_by_name['GeneralUsagePro'] = _GENERALUSAGEPRO

GeneralUsagePro = _reflection.GeneratedProtocolMessageType('GeneralUsagePro', (_message.Message,), dict(
  DESCRIPTOR = _GENERALUSAGEPRO,
  __module__ = 'GeneralUsage_pb2'
  # @@protoc_insertion_point(class_scope:com.fuhu.hadoop.GeneralUsagePro)
  ))
_sym_db.RegisterMessage(GeneralUsagePro)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.fuhu.usagetracking.dtoB\020GeneralUsageData'))
# @@protoc_insertion_point(module_scope)
